name: Deploy
on:
  schedule:
    - cron: "0 4,16 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 23.x
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # 使用默认的 GITHUB_TOKEN 保留凭据，后续可直接 git push origin。
          persist-credentials: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      # 缓存 node_modules，缓存机制参见 GitHub 文档：https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows
      - name: Cache node_modules
        uses: actions/cache@v4 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: blogroll-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      # Wrangler 在构建时会在 workers-site 目录下执行 npm i，因此也要缓存这里的 node_modules
      - name: Cache workers-site/node_modules
        uses: actions/cache@v4
        env:
          cache-name: workers-site-node-modules
        with:
          path: workers-site/node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ env.cache-name }}-${{ hashFiles('workers-site/package-lock.json') }}
      - run: npm i # 执行 Blogroll 的依赖安装
      - run: npm run update # 相当于 node update_files.js，从 Seatable 更新数据到 README.md
        env:
          SEATABLE_API_TOKEN: ${{ secrets.SEATABLE_API_TOKEN }}
      - name: Commit and push if README.md changed
        env:
          DEPLOY_BRANCH: main
        run: |
          if [ -n "$(git status --porcelain README.md)" ]; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add README.md
            git commit -m "update README.md from github actions"
            git push origin HEAD:$DEPLOY_BRANCH
          else
            echo "No changes detected"
          fi
      - run: npm run gen # 相当于 node index.js，生成 opml.xml，opml.json 和 data.json
      - run: npm run build
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_WORKERS_TOKEN }} # 前一步设置的 Secrets 的名称
          # Wrangler Action 也支持使用传统的 Global API Token + Email 的鉴权方式，但不推荐
